title: OpenRA - News Feed # jekyll-feed uses this, so I hardcoded the site title
description: >- # this means to ignore newlines until "baseurl:"
  Open Source reimplementation of Westwood Studios' 2D Command and Conquer games. Play modern versions of Red Alert, Command & Conquer, Dune 2000, and more for free!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://openra.kempf.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: openRA
github_username:  openra
permalink: /:categories/:title/index.html

feed:
  path: /news/atom.html # /news/atom.html -> /news/atom

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "news/*"
    values:
      layout: "news" # set default layout for news posts

# Build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from