name: Sync To Gitee

on:
  push:
    branches:
      - master

jobs:
  linux:
    name: Sync
    runs-on: ubuntu-20.04
    steps:

      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@gitee.com:openra_cn/openra-cn-website.git"
          destination-repo: "git@gitee.com:openra_cn/openra-cn-website.git"